name: build-container

on: push

jobs:
  build-container:
    strategy:
      matrix:
        build-type: [Release, Debug]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker build . --tag ghcr.io/schnellerhase/feedback-vertex-set-container-$(echo ${{ matrix.build-type }} | tr '[A-Z]' '[a-z]'):latest --build-arg BUILD_TYPE=${{ matrix.build-type }}
          # docker run ghcr.io/schnellerhase/feedback-vertex-set-container-$(echo ${{ matrix.build-type }} | tr '[A-Z]' '[a-z]'):latest
          docker push ghcr.io/schnellerhase/feedback-vertex-set-container-$(echo ${{ matrix.build-type }} | tr '[A-Z]' '[a-z]'):latest
